### ISSUE TITLE
[Bug]: Model Replacements for Crossbows not working

### ISSUE THREAD

**Issue by vhound578** [Kizari/Flagrum#204]
### Operating System

Windows 10 64-Bit

### Game Version

Latest Steam Release

### Version

1.6.3

### Description of the bug

1) Either selecting Crossbow from the pre-made weapon replacement menu, or selecting our own crossbow gmdl from the custom preset menu is currently broken with Flagrum
2) The same model can be added as a custom Crossbow into Comrades without issue, but for the main game, we have to use model replacements and currently results in no weapons loading in
3) This can be replicated by importing a crossbow, assigning a blank material to allow exporting, and exporting the crossbow back as an .fmd

Notes:
This same resulting .fmd file can be used to make custom weapons such as comrades crossbows, main game guns and have the model show up in game, but remains invisible when targeting the crossbows via model replacement

It is likely this affects more than just crossbows, as replacing guns resulted in the same issue, but adding it as a new gun worked fine.

### Steps to reproduce the bug

1) Import a bow
2) Set up just a blank material
3) Export bow as fmd untouched
4) Choose either model replacement preset for all crossbows or make a custom preset just for gmdl of we22_000

Note:
Model will work fine as a new crossbow In comrades or as other weapons like a new gun even for the main game.

### Code of Conduct

- [x] I confirm that I have ensured this bug hasn't already been reported in another issue on this repository.
- [x] I confirm that this bug report is pertaining to Flagrum, not an individual mod, the game itself, or an issue with my system or files.
- [x] I confirm that I am using a legitimate copy of the game.
- [x] I confirm that I installed Flagrum with a clean installation of the game, and have not used any tools other than Flagrum to mod my game files.
- [x] If my issue relates to the game itself crashing or exhibiting unexpected behaviour, I confirm that I have tried running a clean unmodded installation of the game to see if this resolves my issue before filing a bug report.

**Comment by Rinual** [comment]
this can be fixed by changing the idiot proofing 

![Image](https://github.com/user-attachments/assets/e2c01e4e-0a00-49dc-94da-bba52df9cd14)

Other users with this issue can either make these changes, themselves by running Flagrum in a developer environment, or I can make a pull request with just this change, which seems like a bad idea as things are generally better if they are idiot proof

**Comment by Rinual** [comment]
This is not fixed in 1.6.4. 
https://github.com/Kizari/Flagrum/commit/660dd71bd25cdcdd1a7c829a576615681ec556f2

<img width="938" height="532" alt="Image" src="https://github.com/user-attachments/assets/47c6fad8-970e-4cf3-8daa-92a248bac110" />

This change removed the section that was labeled idiot proofing, but in order for weapons like crossbows to work, they had to be added **to** that section, making those weapons go through the logic that was provided.

**Comment by Kizari** [comment]
Why would putting crossbows through this logic be beneficial? All it does is forcibly set the weights of every vertex on the model to C_Body, regardless of which bones they were weighted to in the original Blend file.

**Comment by Rinual** [comment]
Currently building the mod in 1.6.4 does not result in a working weapon. It does however using the above edit.

**Comment by Rinual** [comment]
<img width="757" height="569" alt="Image" src="https://github.com/user-attachments/assets/1c1da1b3-8a85-47d7-a745-6f7d80080769" />

Similar to shields, this is also something that used to work with Mod Organizer, apparently

**Comment by Kizari** [comment]
That could be done as an alternative to not showing up at all, but I see no reason why this would behave any differently to if the author simply rigged the whole mesh to C_Body in Blender rather than relying on Flagrum to do it for them. It would be a better approach than trying to add model replacements to the "idiotproofing" block, since there's no specific type for individual models in the official modding system.

I would prefer it was fixed properly if possible though. Do we know if crossbow model replacements specifically worked when created with Mod Organizer? I know model replacements in general were extremely finicky and many just don't work, so it'd be best to know that they were viable under this system before putting more effort into a fix.

**Comment by Rinual** [comment]
Neither I nor the original author of this post need this to be fixed, as the fix I gave them got their mod working as they wanted. The issue persists none the less, but it is not holding back either of us currently from any modding projects as we have a work around in place.

**Comment by Kizari** [comment]
> Rigging everything to C_Body did not result in a working model

Interesting. Might be something to do with the way the guardrails overwrite the bone IDs or bone table that differs from how it translates the rigging on export. In that case, the "correct" solution is likely to figure out what it is about this that makes the difference, and fix it in the exporter itself. Since it's not holding anyone back currently, I won't put it high up the priority list at this stage.

**Comment by Kizari** [comment]
Looks like past me is way ahead of us.

https://github.com/Kizari/Flagrum/blob/b6331f5594156493ce75ff38c09c60b7b268ba52/src/Flagrum.Application/Features/WorkshopMods/Data/BinmodModelReplacer.cs#L32

Only issue is that I had arbitrarily specified weapons would have fewer than 6 bones, but crossbows have 10, hence why they weren't covered by this logic.

Nice easy fix at least!
