### ISSUE TITLE
Forsaken Export issues

### ISSUE THREAD

**Issue by Rinual** [Kizari/Flagrum#89]
Forsaken bulk exports are a bit of a trouble atm, even just trying scripts and nothing else. 

the issue seems to stem from if i am exporting on any folder at this level or above all the way to root, and any of the subdirectories that leads to this folder, flagrum will crash regardless of the exporting file type selected. 
data://asset/environment/area/world/heightmaps
[crash.txt](https://github.com/Kizari/Flagrum/files/12641232/crash.txt)

**Comment by Rinual** [comment]
so prc_tex is the usual crash, and from countless places. this one is dummy.txt 
[crash.txt](https://github.com/Kizari/Flagrum/files/12643940/crash.txt)
from exporting data://content/navimap

**Comment by Lennn888** [comment]
Missing file types (and example location):

- .prc_tex       (data://asset/vfx/game/environment/worldprocedural/world_main/outdata_fog/falldeatharea_paintmask)
- .prtex          (data://asset/environment/area/world/procedural/outdata/flow_sim_cache_single_speed)
- .prmsk         (data://asset/environment/area/world/procedural/outdata/terrainraw)

**Comment by Kizari** [comment]
Found the following missing extensions and added them to Flagrum for 1.5.6:
- .aig
- .prc_tex
- .prmsk
- .prtex
- .wpcd

Obviously some of these were already discovered and listed above, but putting them all into the one list for posterity.

As for dual extensions, `dummy.txt` was the only case found that was not already handled, so have updated the code accordingly for that one as well.

I am now able to dump scripts for the entire game with no crash or exceptions, so I'd say this is solved.

It will be released with Flagrum 1.5.6 when it's ready. Shouldn't be too far away.

**Comment by Lennn888** [comment]
It seems the crash on export is still happening when exporting the whole "data:" folder and subs. I think because:

- .emem
- .backup

**Comment by Kizari** [comment]
I think this may be a separate issue introduced with the new loose file indexing in 1.5.6+. At least this makes sense for `.backup`, but not entirely sure why `.emem` is misbehaving since that's accounted for and as far as I'm aware only exists in packed files. Will need to look into that one, hopefully I can reproduce.

**Comment by Kizari** [comment]
Fixed in Flagrum 1.5.8.
